"""test runnnig migrations

Revision ID: 02b7cf59f5a6
Revises: 73b7f2d85564
Create Date: 2025-08-24 04:09:14.272580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b7cf59f5a6'
down_revision: Union[str, Sequence[str], None] = '73b7f2d85564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
