"""test runnnig migrations

Revision ID: 0cdb95de7f41
Revises: 0d9ce9eb7822
Create Date: 2025-08-24 04:03:09.427849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdb95de7f41'
down_revision: Union[str, Sequence[str], None] = '0d9ce9eb7822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
