"""test runnnig migrations

Revision ID: 0f84881a7c38
Revises: 3ec9ae3fc6af
Create Date: 2025-08-24 22:27:09.129350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f84881a7c38'
down_revision: Union[str, Sequence[str], None] = '3ec9ae3fc6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
