"""test runnnig migrations

Revision ID: 7704bdb7410a
Revises: e7d5f7fc53ac
Create Date: 2025-08-24 22:35:05.427348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7704bdb7410a'
down_revision: Union[str, Sequence[str], None] = 'e7d5f7fc53ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
