"""test runnnig migrations

Revision ID: 9a9e04c9a81c
Revises: a5a3ad4c2e0b
Create Date: 2025-08-24 04:04:14.624324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9e04c9a81c'
down_revision: Union[str, Sequence[str], None] = 'a5a3ad4c2e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
