"""test runnnig migrations

Revision ID: a5a3ad4c2e0b
Revises: 0cdb95de7f41
Create Date: 2025-08-24 04:03:14.498680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a3ad4c2e0b'
down_revision: Union[str, Sequence[str], None] = '0cdb95de7f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
