"""test runnnig migrations

Revision ID: fba44f3e45ac
Revises: 5a2feb0ca930
Create Date: 2025-09-03 00:13:43.504553

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fba44f3e45ac"
down_revision: Union[str, Sequence[str], None] = "5a2feb0ca930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
